name: SBOM Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # 3. Install Microsoft's SBOM Tool
    - name: Install SBOM Tool
      run: |
        curl -LO https://github.com/microsoft/sbom-tool/releases/download/v1.2.3/sbom-tool-linux-x64
        chmod +x sbom-tool-linux-x64
        mv sbom-tool-linux-x64 /usr/local/bin/sbom-tool

    # 4. Generate SBOM
    - name: Generate SBOM
      run: |
        sbom-tool generate -b . -bc . -pn "Lambda Uploader" -pv "1.0.0" -ps "Open Source Project"

    # 5. Validate SBOM
    - name: Validate SBOM
      run: |
        sbom-tool validate -i _manifest/spdx_2.2

    # 6. Upload SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: _manifest/spdx_2.2
