name: Python Build and Artifact Workflow with SBOM

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build or package the project
    - name: Build the project
      run: |
        python setup.py sdist bdist_wheel
        mkdir buildOutput
        mv dist/* buildOutput/

    # Step 5: Download and set up SBOM Tool
    - name: Install SBOM Tool
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool

    # Step 6: Generate SBOM
    - name: Generate SBOM
      run: |
        $RUNNER_TEMP/sbom-tool generate \
          -b ./buildOutput \
          -bc . \
          -pn "Python Project" \
          -pv "1.0.0" \
          -ps "MyCompany" \
          -nsb "https://sbom.mycompany.com" \
          -V Verbose
      env:
        DOTNET_NOLOGO: true

    # Step 7: Upload Build and SBOM Artifacts
    - name: Upload Build and SBOM Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: python-build-and-sbom
        path: |
          buildOutput
          _manifest
